version: '3.7'

services:
  postgres:
    image: postgres:15.5-alpine
    container_name: store_db
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_api
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres