# Generated by Django 3.2.22 on 2024-01-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
