# Generated by Django 3.2.22 on 2024-01-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orders_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_items',
        ),
    ]
