# Generated by Django 3.2.22 on 2024-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20240112_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
